/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 diamond_engagement_ring.glb 
Author: assetfactory (https://sketchfab.com/assetfactory)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/diamond-engagement-ring-76c5820088d34eae934a23d043d1fec3
Title: Diamond Engagement Ring
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/diamond_engagement_ring.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.Crystal} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Metal} />
      </group>
    </group>
  )
}

useGLTF.preload('/diamond_engagement_ring.glb')
