/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Legend (https://sketchfab.com/Legend_01)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/deadpool-marvel-free-00b3f2ac5dac4e448ff73f0991ecb660
Title: DEADPOOL MARVEL (FREE)
*/

import React, { useRef } from "react";
import { useGLTF, useFrame } from "@react-three/drei";

function Model(props) {
  // Load the GLTF model
  const { nodes, materials } = useGLTF("/models/Deadpool/deadpool_marvel_free.glb");

  // Reference for animation
  const helix = useRef();

  // Constant speed for rotation animation
  const HELIX_SPEED = 0.01;

  // Animate the helix (or other parts if needed)
  useFrame(() => {
    if (helix.current) {
      helix.current.rotation.x += HELIX_SPEED;
    }
  });

  return (
    <group {...props} dispose={null} ref={helix}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials.material_0}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_5.geometry}
        material={materials.material_0}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_6.geometry}
        material={materials.material_0}
      />
    </group>
  );
}

useGLTF.preload("/models/Deadpool/deadpool_marvel_free.glb");

export default Model;