/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 lilith.glb 
Author: Mateusz Woliński (https://sketchfab.com/jeandiz)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/lilith-823bb66e894d4d31bfa4e3b238902c8a
Title: 𝕷𝖎𝖑𝖎𝖙𝖍
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import gsap from 'gsap'

function Model(props) {
  const { nodes, materials } = useGLTF('/lilith.glb')
  const tl = gsap.timeline({ repeat: -1, repeatDelay: 0.5 })
  return (
    <group {...props} dispose={null} >
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[-4.5, 2.5, 3.7  ]} rotation-x={-Math.PI / 0.5} scale={[4, 4, 4]}>
          <mesh geometry={nodes.Object_4.geometry} material={materials.Body} />
          <mesh geometry={nodes.Object_5.geometry} material={materials.Body_0} />
          <mesh geometry={nodes.Object_6.geometry} material={materials.Body_1} />
          <mesh geometry={nodes.Object_7.geometry} material={materials.Threads} />
          <mesh geometry={nodes.Object_8.geometry} material={materials.Threads_0} />
          <mesh geometry={nodes.Object_9.geometry} material={materials.Threads_1} />
          <mesh geometry={nodes.Object_10.geometry} material={materials.Clothes} />
          <mesh geometry={nodes.Object_11.geometry} material={materials.Leviathan} />
          <mesh geometry={nodes.Object_12.geometry} material={materials.Threads_2} />
          <mesh geometry={nodes.Object_13.geometry} material={materials.BlackHalo} />
          <mesh geometry={nodes.Object_14.geometry} material={materials.WhiteHalo} />
          <mesh geometry={nodes.Object_15.geometry} material={materials.Clothes_0} />
          <mesh geometry={nodes.Object_16.geometry} material={materials.Threads_3} />
          <mesh geometry={nodes.Object_17.geometry} material={materials.Threads_4} />
          <mesh geometry={nodes.Object_18.geometry} material={materials.Clothes_1} />
          <mesh geometry={nodes.Object_19.geometry} material={materials.Leviathan_0} />
          <mesh geometry={nodes.Object_20.geometry} material={materials.Leviathan_0} />
          <mesh geometry={nodes.Object_21.geometry} material={materials.Clothes_1} />
          <mesh geometry={nodes.Object_22.geometry} material={materials.Threads_4} />
          <mesh geometry={nodes.Object_23.geometry} material={materials.Threads_3} />
          <mesh geometry={nodes.Object_24.geometry} material={materials.Clothes_0} />
          <mesh geometry={nodes.Object_25.geometry} material={materials.WhiteHalo} />
          <mesh geometry={nodes.Object_26.geometry} material={materials.BlackHalo} />
          <mesh geometry={nodes.Object_27.geometry} material={materials.Threads_2} />
          <mesh geometry={nodes.Object_28.geometry} material={materials.Leviathan} />
          <mesh geometry={nodes.Object_29.geometry} material={materials.Clothes} />
          <mesh geometry={nodes.Object_30.geometry} material={materials.Threads_1} />
          <mesh geometry={nodes.Object_31.geometry} material={materials.Threads_0} />
          <mesh geometry={nodes.Object_32.geometry} material={materials.Threads} />
          <mesh geometry={nodes.Object_33.geometry} material={materials.Body_1} />
          <mesh geometry={nodes.Object_34.geometry} material={materials.Body_0} />
          <mesh geometry={nodes.Object_35.geometry} material={materials.Body} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/lilith.glb')

export default Model;